sudo: required
language: android
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - yes | sdkmanager tools

before_script:
  - chmod +x scripts/*.sh
  - chmod +x scripts/*.py

script:
  - ./gradlew build
  - scripts/review.sh